package main

import "testing"

func TestHandleErrorDemo1(t *testing.T) {
	handleErrorDemo1()
}
